# NUMPY

In [1]:
import numpy as np

In [2]:
#CREATING ARRAYS
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [15]:
x = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

In [9]:
#MULTIDIMENSIONAL ARRAY
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [13]:
w = np.array([[4, 5, 6], [10, 11, 12], [20, 21, 22]])
w

array([[ 4,  5,  6],
       [10, 11, 12],
       [20, 21, 22]])

In [24]:
#ARRAY DIMENSION
np.shape(m)

(3, 3)

In [25]:
np.shape(w)

(3, 3)

In [40]:
n = np.arange(0, 50, 2) # start at 0, stops before 50 (don't include 30), count in 2's
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [42]:
np.shape(n)

(25,)

In [48]:
#RESHAPE RETURNS AN ARRAY WITH THE SAME DATA WITH A NEW SHAPE
n.reshape(5, 5) # This reshapes the array to be a 5 x 5 array

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [57]:
#ONES = This returns a new array of given shape and type, filled with ones
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [63]:
#ZEROS = This returns a new array of given shape and type, filled with zeros
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [66]:
#EYE =This returns a 2-D array witg Ones on the Diagonal side and Oneson every other side
np.eye(2, 3)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [67]:
np.eye(2, 3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [71]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# OPERATIONS

## Use +, -, /, * and ² to performelement wise addition, subtraction, 
## division, multiplication and power


In [17]:
print(x)
print(y)

[1 2 3]
[4 5 6]


In [13]:
print(x + y) # elementwise addition [1 2 3] + [4 5 6] = [5 7 9]
print(x - y) # elementwise subtraction [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [18]:
print(x * y) #elementwise multiplication [1 2 3] * [4 5 6] = [4 10 18]
print(x / y) #elementwise divition [1 2 3] / [4 5 6] = [0.25 0.4 0.5]

[ 4 10 18]
[0.25 0.4  0.5 ]


In [10]:
print(x ** 2) # elementwise power [1 2 3] ^2 = [1 4 9]

[1 4 9]


In [21]:
z = np.array([y, y ** 2]) #multidimensional array
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [16]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

# Math Functions

Numpy has many built in math functions that can be performed on arrays

In [22]:
a = np.array([-9, 3, 1, 6, 5])
a

array([-9,  3,  1,  6,  5])

In [32]:
a.sum()

6

In [41]:
b = 0
for x in a: 
    #b += x
    b = b + x
    #b = 0 + (-9)= -9, b= - 9 +3 = -6
b

6

In [51]:
a.max()

6

In [53]:
a.min()

-9

In [54]:
a.mean()

1.2

In [56]:
a.std()

5.381449618829484

Argmax and Argmin returns the index of the Maximum and the Minimum value of the array

In [57]:
a.argmax()

3

In [59]:
a.argmin()

0

Indexing and Slicing

In [44]:
s = np.arange(0, 13, 1) ** 2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [45]:
s[0], s[4], s[-1]

(0, 16, 144)

In [68]:
g = np.arange(5, 11, 1) ** 3
g

array([ 125,  216,  343,  512,  729, 1000], dtype=int32)

In [72]:
s[0], s[4], s[-1]

(0, 16, 144)

In [73]:
s[1:5] #start from the 2nd element to the 5th element

array([ 1,  4,  9, 16], dtype=int32)

In [48]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [5]:
r[2]

array([12, 13, 14, 15, 16, 17])

In [6]:
r[2, 2]

14

In [49]:
r[3]

array([18, 19, 20, 21, 22, 23])

In [54]:
print(r[3, 3:7])
print(r[4, 2:6])

[21 22 23]
[26 27 28 29]


In [62]:
r [r > 30]

array([31, 32, 33, 34, 35])